# Generated by Django 3.2.21 on 2023-09-23 18:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('platform', models.CharField(max_length=256, verbose_name='Nome da plataforma')),
                ('platform_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxa da plataforma')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property', verbose_name='UUID do Imóvel')),
            ],
            options={
                'verbose_name': 'ad',
                'verbose_name_plural': 'ads',
                'ordering': ['uuid', 'property', 'platform', 'platform_rate'],
            },
        ),
    ]
